/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIHello */

#ifndef _Included_jni_JNIHello
#define _Included_jni_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIHello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNIHello_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNIHello
 * Method:    plusInteger
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_JNIHello_plusInteger
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
